### ISSUE TITLE
Phantasy Star IV Bugfix

### ISSUE THREAD

**Issue by Arthandas** [lory90/ps4disasm#13]
Hi, sorry for posting in the "issues" tab but this was the only way I found of contacting you. I wanted to ask if you could make your Phantasy Star IV Bugfix romhack compatible with the Steam version? The steam version comes with an uncompressed rom which can be easily extracted and played on any other emulator so patching it should also be possible. Thanks in advance!

**Comment by lory90** [comment]
I'm going to close this issue, but I included my email so you can reach me that way.
Unfortunately, I'm not familiar with the Steam version...my hack is based on the original Genesis version, so it would require an entirely different patch; I could be wrong since I don't have the Steam ROM to confirm.....
